name: Trigger Jenkins Build

on:
  push:
    branches:
      - master # 仅当推送到 `main` 分支时触发
  workflow_dispatch: # 允许手动触发

jobs:
  trigger-jenkins-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Trigger Jenkins build
        run: |
          curl -v -X GET "${JENKINS_URL}/job/GenBlog/build?token=${API_TOKEN}"
        env:
          JENKINS_URL: https://jenkins.zqzqsb.cn
          API_TOKEN: ${{ secrets.JENKINS_API_TOKEN }}
